axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.8
  y: 0.0
scale_linear_turbo:
  x: 0.8
  y: 0.8
axis_angular:
  yaw: 0
scale_angular:
  yaw: 2.2
scale_angular_turbo:
  yaw: 0
enable_button: 7
enable_turbo_button: 6
