axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.4
  y: 0.0
scale_linear_turbo:
  x: 0.4
  y: 0.4
axis_angular:
  yaw: 0
scale_angular:
  yaw: 1.2
scale_angular_turbo:
  yaw: 0
enable_button: 5
enable_turbo_button: 4
